### PR TITLE
Added compatibility with TailwindCSS 1.4

### PR DESCRIPTION
**Pull request by vesper8**
Also in the right format this time : ) sorry bout last time
Also removed classes with prefixes (such as hover: and focus:) that were causing the prefix to be incorrectly applied twice
Also added form classes from Tailwind UI

### CODE REVIEW

**Comment by kiliman** [comment]
I added you as a collaborator so you can merge it. Thanks!

**Comment by vesper8** [comment]
I feel silly for asking but I'm not well versed in merging PRs on other people's projects.. I don't see a merge button anywhere.. I do see a warning saying `Only those with write access to this repository can merge pull requests.`

**Comment by vesper8** [comment]
oh nevermind! It's because I hadn't seen and accepted the invitation yet : ) thanks!

**Comment by kiliman** [comment]
Thanks for helping out... I've been busy with other work, but I'm starting to get back into doing stuff with Tailwind UI, so I'll probably start including more things that help me automate the process.

**Pull request merged**
